workflows:
  android-release:
    name: Build Android Release with Firebase
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
      android:
        image: default
    scripts:
  - name: Ensure android folder
    script: flutter create .
  - name: Decode google-services.json
    script: |
      if [ -n "$GOOGLE_SERVICES_JSON" ]; then
        echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      fi
  - name: Get dependencies
    script: flutter pub get
  - name: Build APK
    script: flutter build apk --release
artifacts:
  - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - youremail@example.com
